### ISSUE TITLE
Exception handling started ==> cause:Error 201,1,30000,0,5,BB9030011AC4202 172.17.0.3 3000: Index not found; nested exception is com.aerospike.client.AerospikeException: Error 201,1,30000,0,5,BB9030011AC4202 172.17.0.3 3000: Index not found

### ISSUE THREAD

**Issue by vikas8910** [aerospike-community/spring-data-aerospike#337]
i am using version of Spring Data Aerospike is 2.4.0.RELEASE and crud repository.

got this error on this operation : repo.findByBankIdAndMeCode("A","123");

**Comment by roimenashe** [comment]
@vikas8910 
In order to query in Spring Data Aerospike you need to create a secondary index on the field/bin you're trying to query or alternatively you can enable scans (as you mentioned in the second issue - #336).

I replied on your second issue on how to enable scans.
As for secondary indexes - here is a blog post that explains how to create a secondary index in Spring Data Aerospike:
https://medium.com/aerospike-developer-blog/how-to-create-secondary-index-in-spring-data-aerospike-e19d7e343d7c

I hope that helps, please keep us updated.

**Comment by vikas8910** [comment]
> @vikas8910 In order to query in Spring Data Aerospike you need to create a secondary index on the field/bin you're trying to query or alternatively you can enable scans (as you mentioned in the second issue - #336).
> 
> I replied on your second issue on how to enable scans. As for secondary indexes - here is a blog post that explains how to create a secondary index in Spring Data Aerospike: https://medium.com/aerospike-developer-blog/how-to-create-secondary-index-in-spring-data-aerospike-e19d7e343d7c
> 
> I hope that helps, please keep us updated.

i have created secondary level index on bins by using below way....

create index idx_RelayBatchFile_bankId on relay.RelayBatchFile (bankId) String

is it okay?

**Comment by roimenashe** [comment]
@vikas8910 
This is the syntax if you are using AQL:
`CREATE [indextype] INDEX <index> ON <ns>[.<set>] (<bin>) <type>`

You can also check if the index was created using `SHOW INDEXES [<ns>]`.
For more information about index creation using AQL check out: https://docs.aerospike.com/tools/aql/index_management

The link i've added in my previous comment describes how to create a secondary index in Spring Data Aerospike.

Did you create the index successfully? Please keep us updated/close the issue if no longer relevant.

**Comment by vikas8910** [comment]
> SHOW INDEXES

Thanks for your help :)
