### ISSUE TITLE
 How to modify ttl for all records in table using aql

### ISSUE THREAD

**Issue by vikas8910** [aerospike-community/spring-data-aerospike#398]
Urgent : How to modify ttl for all records in table using aql? 
Thanks in advance.

**Comment by roimenashe** [comment]
@vikas8910 
This is not the right place for AQL related questions since this is the `Spring Data Aerospike` repository.
But from the quick research I performed the way to go for changing TTL using AQL is with UDFs.

Check out this StackOverFlow question:
https://stackoverflow.com/questions/44988253/update-ttl-for-all-records-in-aerospike

And this article:
https://discuss.aerospike.com/t/how-to-modify-ttl-using-udf/5608

Im closing this issue because it isn't the right place.
If this answer isn't sufficient feel free to open a GitHub issue in AQL's official repository:
https://github.com/aerospike/aql

Or a StackOverFlow question (with `Aerospike` tag)/Aerospike forum question.
Good luck :)
