### ISSUE TITLE
Unable to override base repository implementation

### ISSUE THREAD

**Issue by lfarmer** [aerospike-community/spring-data-aerospike#400]
Hi,

I am trying to override the base repository implementation so that I can hook into the batch read functionality available within operations.

I have put together an [example repository](https://github.com/lfarmer/spring-data-aerospike-example) to demonstrate my issue.  

Tested by running the [test](https://github.com/lfarmer/spring-data-aerospike-example/blob/main/src/test/java/com/example/ReactiveCustomerRepositoryTest.java) in debug, with a breakpoint within both the SimpleReactiveAerospikeRepository and my own.  

Seems it never gets picked up?  
Am I missing something?  

I followed the guide in [spring-data-commons](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.customize-base-repository)

TIA
Lea

**Comment by roimenashe** [comment]
Hi @lfarmer,

I didn't check the logic of your code but one thing I noticed is that your project doesn't contain a configuration class.
In order to interact with Aerospike using Spring Data Aerospike you'll have to create a configuration class that includes the at least the Aerospike server IP address and port.

Check out this blog post of how to setup a Spring Data Aerospike project (it's non-reactive but the principles are the same, just switch to reactive configuration class instead): https://medium.com/aerospike-developer-blog/simple-web-application-using-java-spring-boot-aerospike-database-and-docker-ad13795e0089

This medium article also contains a link to a GitHub example project with a configuration class (again, non-reactive in this example but its similar - just replace the extended class).

There is also this article about setting up a reactive Spring Data Aerospike project: https://medium.com/aerospike-developer-blog/spring-data-aerospike-reactive-repositories-fb6478acea41.

**Comment by roimenashe** [comment]
You'r `application.properties` file seems to be empty, where did you configure the IP address and port of the Aerospike database?

The minimal configuration of `spring-boot-starter-data-aerospike-reactive` requires couple of configurations: https://github.com/aerospike-community/spring-data-aerospike-starters#minimal-configuration

**Comment by roimenashe** [comment]
@lfarmer My bad, saw it under tests, let me run your tests - i'll keep you updated.

**Comment by roimenashe** [comment]
@lfarmer
After changing your `bootstrap.application` to localhost:3000 (where my Aerospike is running):

```
embedded.containers.enabled=true

embedded.aerospike.enabled=true

spring.aerospike.hosts=localhost:3000

spring.data.aerospike.namespace=test
```

And now I see that records are inserted to Aerospike and tests are passing:
<img width="214" alt="Screen Shot 2022-07-14 at 15 59 48" src="https://user-images.githubusercontent.com/33356310/178988266-c009838f-0892-4d18-b0b3-31e155a2bf57.png">

**Comment by lfarmer** [comment]
Hi @roimenashe 

The functionality of saving / retrieving was never in question...   the test will pass.  

But as described in my original message:

> I am trying to override the base repository implementation so that I can hook into the batch read functionality available within operations.

This is so I can utilise batch reads as implemented [here](https://github.com/lfarmer/spring-data-aerospike-example/blob/main/src/main/java/com/example/BatchReactiveAerospikeRepositoryImpl.java)

Essentially the way of providing a different base repository implementation through the annotation, doesn't seem to work.

Please see my configured one [here](https://github.com/lfarmer/spring-data-aerospike-example/blob/main/src/main/java/com/example/SpringDataAerospikeExampleApplication.java)

**Comment by roimenashe** [comment]
@lfarmer 
After changing `@EnableAerospikeRepositories` to `@EnableReactiveAerospikeRepositories` on this line: https://github.com/lfarmer/spring-data-aerospike-example/blob/main/src/main/java/com/example/SpringDataAerospikeExampleApplication.java#L8

The debugger goes to your custom implementation instead of the `SimpleReactiveAerospikeRepository`.

**Comment by lfarmer** [comment]
Hi @roimenashe,  🤦‍♂️  -  Can't believe I missed that.... Thanks for your time and apologies for raising this issue based on incorrect configuration

**Comment by roimenashe** [comment]
@lfarmer 
No problem!
